### ISSUE TITLE
Cannot index string with string "targetDrv"

### ISSUE THREAD

**Issue by henrywong-crypto** [divnix/std-action#47]
Hi, I am trying to use the main branch
```yaml
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v24
        with:
          nix_conf: experimental-features = nix-command flakes
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Standard Discovery
        uses: divnix/std-action/discover@main
        id: discovery
```
But I got the following error
```
Check for proviso ...
  Check proviso for all 6 'build' action(s) ...
  ... checking //REDACTED/REDACTED/REDACTED:buildjq: error (at <stdin>:1): Cannot index string with string "targetDrv"
  jq: error (at <stdin>:1): Cannot index string with string "targetDrv"
   - drop it.
  ... checking //REDACTED/REDACTED/REDACTED:buildjq: error (at <stdin>:1): Cannot index string with string "targetDrv"
  jq: error (at <stdin>:1): Cannot index string with string "targetDrv"
   - drop it.
  ... checking //REDACTED/REDACTED/REDACTED:buildjq: error (at <stdin>:1): Cannot index string with string "targetDrv"
  jq: error (at <stdin>:1): Cannot index string with string "targetDrv"
   - drop it.
  ... checking //REDACTED/REDACTED/REDACTED:buildjq: error (at <stdin>:1): Cannot index string with string "targetDrv"
  jq: error (at <stdin>:1): Cannot index string with string "targetDrv"
   - drop it.
  ... checking //REDACTED/REDACTED/REDACTED:buildjq: error (at <stdin>:1): Cannot index string with string "targetDrv"
  jq: error (at <stdin>:1): Cannot index string with string "targetDrv"
   - drop it.
  ... checking //REDACTED/REDACTED/REDACTED:buildjq: error (at <stdin>:1): Cannot index string with string "targetDrv"
  Continue with 0 'build' action(s).
```
Please help
